---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-system-admission-token
  namespace: ingress-nginx-system
  annotations:
    kubernetes.io/service-account.name: ingress-nginx-system-admission
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-system-token
  namespace: ingress-nginx-system
  annotations:
    kubernetes.io/service-account.name: ingress-nginx-system
type: kubernetes.io/service-account-token
