apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx-system
    app.kubernetes.io/instance: ingress-nginx-system
    app.kubernetes.io/component: controller
  name: ingress-nginx-system
  namespace: ingress-nginx-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx-system-admission
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: ingress-nginx-system
    app.kubernetes.io/instance: ingress-nginx-system
    app.kubernetes.io/component: admission-webhook
  namespace: ingress-nginx-system
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-system-admission-token
  namespace: ingress-nginx-system
  annotations:
    kubernetes.io/service-account.name: ingress-nginx-system-admission
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-system-token
  namespace: ingress-nginx-system
  annotations:
    kubernetes.io/service-account.name: ingress-nginx-system
type: kubernetes.io/service-account-token
